const images = {
  // expetitlewordmark: require('../assets/images/expetitlewordmark/expetitlewordmark.png'),
  // tick: require('../assets/images/tick.png'),
  logo: require('../../Assets/Images/logo.png'),
  arrow: require('../../Assets/Images/arrow.png'),
  arrowBlack: require('../../Assets/Images/arrowBlack.png'),
  bookAppointment: require('../../Assets/Images/appointment.png'),
  onlineBooking: require('../../Assets/Images/booking.png'),
  bookLabTest: require('../../Assets/Images/labTest.png'),
  clinicalProcedure: require('../../Assets/Images/medicalProcdure.png'),
  searchDisease: require('../../Assets/Images/searchDisease.png'),
  medicalHistory: require('../../Assets/Images/medicalHistory.png'),
  doctor: require('../../Assets/Images/doctor.png'),
  // ui: require('../assets/images/ui.png'),
  // uiclosed: require('../assets/images/uiclosed.png'),
  // loader: require('../assets/images/loader.gif'),
  // logout: require('../assets/images/logout.png'),
  // Calandar: require('../assets/images/Details/Calandar.png'),
  // Contacts: require('../assets/images/Details/Contacts.png'),
  // ContactsList: require('../assets/images/Details/ContactsList.png'),
  // Documents: require('../assets/images/Details/Documents.png'),
  // Status: require('../assets/images/Details/Status.png'),
  // File: require('../assets/images/Details/File.png'),
};
export default images;
