export const ADD_APPOINTMENT = 'app/Doctor/ADD_APPOINTMENT';
export const ADD_APPOINTMENT_SUCCESS = 'app/Doctor/ADD_APPOINTMENT_SUCCESS';
export const ADD_APPOINTMENT_FAILED = 'app/Doctor/ADD_APPOINTMENT_FAILED';
