export const UPDATE_PROFILE = 'app/DOCTOR_FORM/UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'app/DOCTOR_FORM/UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'app/DOCTOR_FORM/UPDATE_PROFILE_FAIL';
